name: ligo
channels:
  - conda-forge
dependencies:
  - ipykernel=6.29 #needed?
  - jupyterlab  # needed for binder jupyter interface
  - numpy==2.0
  - scipy==1.13
  #- h5py==3.12
  - json5=0.9
  #- matplotlib==3.9
  - pip
  - pip:
    - h5py==3.12
    - matplotlib==3.9
